### ISSUE TITLE
Unable to pass a function to :tooltip-formatter

### ISSUE THREAD

**Issue by sunscreem** [s-sasaki-0529/vue-slider-component#3]
#### Describe the bug

I'm trying to format my tool tips using the following function:

```js
const formatter = (value) => {
  if (!value) {
    return "";
  }
  return "£" + Math.round(value / 1000) + "k";
}
```

When I apply this with `:tooltip-formatter="formatter"` I get:

```
Invalid prop: type check failed for prop "tooltipFormatter". Expected String | Array | Object, got Function
```

#### Environment (If you feel unrelated, please delete the block)

 - Vue version: v3.3.4
 - Component Version: v0.1.2

**Comment by s-sasaki-0529** [comment]
@sunscreem
Thanks for the report!

I've fixed it and will release it as soon as possible.

**Comment by s-sasaki-0529** [comment]
v0.1.4 has shipped.

**Comment by sunscreem** [comment]
@s-sasaki-0529 Finally got time to check this. Working perfectly now - thank you!
