### ISSUE TITLE
Cannot read properties of null (reading 'isCE')   at renderSlot 

### ISSUE THREAD

**Issue by Valgri** [s-sasaki-0529/vue-slider-component#4]
#### Describe the bug

![image](https://github.com/s-sasaki-0529/vue-slider-component/assets/28981859/219631bb-bd1b-462b-bb25-774d42f1b064)

That's the error. I tried removing the slot, it doesn't help. I use vite for building. -  "@quasar/app-vite": "^1.3.0";

It's the same situation in the main library. Everything worked fine on webpack, when moving to vite it gives an error, tried all possible ways to use one version of vue in the project, as I thought that the problem in the conflict of two vue instances, did not help. Could you please fix this?

#### Environment (If you feel unrelated, please delete the block)

 - OS & Version: Linux
 - Vue version: v3.4.15
 - Component Version: v0.1.2

**Comment by s-sasaki-0529** [comment]
@Valgri 

Thanks for the report!

Sorry. I don't have time to investigate, but can you provide a reproduction repository in the meantime?

**Comment by Valgri** [comment]
@s-sasaki-0529  I have fixed it. Used a vite 5 beta.
https://github.com/quasarframework/quasar/issues/16896#issuecomment-1941141249

**Comment by s-sasaki-0529** [comment]
@Valgri This issue was probably resolved in [v1.0.0](https://github.com/s-sasaki-0529/vue-slider-component/releases/tag/v1.0.0). If it continues to occur, please open it again.
