### ISSUE TITLE
Issues with SSR

### ISSUE THREAD

**Issue by genu** [s-sasaki-0529/vue-slider-component#6]
Usage in Nuxt fails due to the dependency on `document`

There should be a built in check for SSR to ignore style injection in a node context.

**Comment by s-sasaki-0529** [comment]
@genu @whipsterCZ @michelle-article
This issue was probably resolved in [v1.0.0](https://github.com/s-sasaki-0529/vue-slider-component/releases/tag/v1.0.0). If it continues to occur, please open it again.
